[project]
# Whether to enable telemetry (default: true). No personal data is collected.
enable_telemetry = false

# List of environment variables to be provided by each user to use the app.
user_env = []

# Duration (in seconds) during which the session is saved when the connection is lost
session_timeout = 3600

# Enable third parties caching (e.g LangChain cache)
cache = true

# Authorized origins
allow_origins = ["*"]

# Follow symlink for asset mount (see https://github.com/Chainlit/chainlit/issues/317)
# follow_symlink = false

[features]
# Process and display mathematical expressions. This can affect performance on large conversations.
latex = false

# Authorize users to upload files with messages
upload_file = true

# Allows user to use speech to text
[features.speech_to_text]
enabled = false
# See all languages here https://github.com/openai/whisper/blob/main/whisper/tokenizer.py
language = "en"

[features.audio]
# Allows user to use audio messages
enabled = false
# Max number of seconds for audio recording
max_duration = 60
# Min number of seconds for audio recording
min_duration = 1
# Sampling frequency for audio recording
sample_rate = 44100

[UI]
# Name of the app and chatbot.
name = "AI Discovery Cards Agents"

# Show the readme while the conversation is empty.
show_readme_as_default = true

# Description of the app and chatbot. This is used for HTML tags.
description = "AI Discovery Cards facilitator with multiple expert agents for design thinking workshops"

# Large size content are by default collapsed for a cleaner ui
default_collapse_content = true

# The default value for the expand messages settings.
default_expand_messages = false

# Hide the chain of thought details from the user in the UI.
hide_cot = false

# Link to your github repo. This will add a github button in the UI's header.
github = "https://github.com/jmservera/AIDiscoveryCardsFacilitator"

# Specify a CSS file that can be used to customize the user interface.
# The CSS file can be served from the public directory or via an external link.
# custom_css = "/public/style.css"

# Specify a Javascript file that can be used to customize the user interface.
# The Javascript file can be served from the public directory.
# custom_js = "/public/script.js"
# custom_js="https://cdn.jsdelivr.net/npm/mermaid@11/dist/mermaid.esm.min.mjs"

# Specify a custom font url.
# custom_font = "https://fonts.googleapis.com/css2?family=Inter:wght@400;500;700&display=swap"

# Specify a custom meta image url.
# custom_meta_image_url = "https://chainlit-cloud.s3.eu-west-3.amazonaws.com/logo/chainlit_banner.png"

# Specify a custom build directory for the UI.
# This is relative to the chainlit package directory.
# custom_build = "./public/build"

[meta]
generated_by = "jmservera"
