api_key: null
cookie:
  expiry_days: 30
  key: test-key-or-nothing
  name: AIDCFacilitator
credentials:
  usernames:
    jdoe:
      email: johndoe@contoso.com
      failed_login_attempts: 0
      first_name: John
      last_name: Doe
      logged_in: false
      password: $2b$12$DOm8HmKD9xq49STJQbQpD./gZqmDuf3gx7jL2RhUnHFmcJg51jAA2
      roles:
      - user
    jsmith:
      email: jsmith@gmail.com
      failed_login_attempts: 0
      first_name: John
      last_name: Smith
      logged_in: true
      password: $2b$12$kZg/2x3x2Arb2wQhee/pXOxNkahOWECQMQ/qw/7sGrkEcmRN7lkeK
      roles:
      - admin
