name: CI - Compilation and Testing
on:
  workflow_dispatch:
  pull_request:
    paths:
      - "src/**"
      - ".github/workflows/ci.yml"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: install dependencies
        run: |
          pip install --upgrade pip
          pip install -r src/requirements.txt
        shell: bash

      - name: compile
        run: python -m compileall src/
        shell: bash
